-- Adicionar campos de endereço e notas à tabela users
ALTER TABLE users
ADD COLUMN IF NOT EXISTS address VARCHAR(255),
ADD COLUMN IF NOT EXISTS city VARCHAR(100),
ADD COLUMN IF NOT EXISTS state VARCHAR(2),
ADD COLUMN IF NOT EXISTS zip VARCHAR(10),
ADD COLUMN IF NOT EXISTS notes TEXT;
